/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package lkh.dot.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GRAPH = 5;
  /** RegularExpression Id. */
  int DIGRAPH = 6;
  /** RegularExpression Id. */
  int INIT = 7;
  /** RegularExpression Id. */
  int RARROW = 8;
  /** RegularExpression Id. */
  int LABEL = 9;
  /** RegularExpression Id. */
  int ID = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"graph\"",
    "\"digraph\"",
    "\"init_\"",
    "\"->\"",
    "\"label\"",
    "<ID>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"[shape=\\\"point\\\"]\"",
    "\"[shape=\\\"doublecircle\\\"]\"",
    "\"[\"",
    "\"=\"",
    "\"\\\"\"",
    "\"]\"",
  };

}
