/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package lkh.expression.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPLIES = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int KH = 9;
  /** RegularExpression Id. */
  int PROP = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"implies\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"kh\"",
    "<PROP>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
