/* Generated By:JavaCC: Do not edit this line. LTSParserConstants.java */
package lkh.lts.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LTSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGRAPH = 5;
  /** RegularExpression Id. */
  int RARROW = 6;
  /** RegularExpression Id. */
  int LABEL = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int OPEN_QUOTE = 9;
  /** RegularExpression Id. */
  int QUOTED_ID = 10;
  /** RegularExpression Id. */
  int CLOSE_QUOTE = 11;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LABEL = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"digraph\"",
    "\"->\"",
    "\"label\"",
    "<ID>",
    "\"\\\"\"",
    "<QUOTED_ID>",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"[\"",
    "\"=\"",
    "\"]\"",
  };

}
