/* LTSParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. LTSParserTokenManager.java */
package lkh.lts.parser;
import lkh.lts.HashMapLTS;

/** Token Manager. */
@SuppressWarnings ("unused")
public class LTSParserTokenManager implements LTSParserConstants {

  protected SimpleCharStream input_stream;
  int curLexState = DEFAULT;
  int defaultLexState = DEFAULT;
  int jjmatchedKind;
  int jjmatchedPos;
  protected int curChar;

  private final int[] jjrounds = new int[1];
  private final int[] jjstateSet = new int[2];
  private final StringBuilder jjimage = new StringBuilder();
  private int jjimageLen;
  private int lengthOfMatch;
  int jjnewStateCnt;
  int jjround;

  /** Lexer state names. */
  public static final String[] lexStateNames = { "DEFAULT", "IN_LABEL" };

  /** Lex State array — OPEN_QUOTE (9) switches to IN_LABEL, CLOSE_QUOTE (11) switches to DEFAULT */
  public static final int[] jjnewLexState = {
    -1, -1, -1, -1, -1, -1, -1, -1, -1, IN_LABEL, -1, DEFAULT, -1, -1, -1, -1, -1, -1,
  };

  static final long[] jjtoToken   = { 0x3ffe1L };
  static final long[] jjtoSkip    = { 0x1eL    };
  static final long[] jjtoSpecial = { 0x0L     };
  static final long[] jjtoMore    = { 0x0L     };

  public static final String[] jjstrLiteralImages = {
    "",      // 0  EOF
    null,    // 1  " "
    null,    // 2  \n
    null,    // 3  \t
    null,    // 4  \r
    "\144\151\147\162\141\160\150", // 5  digraph
    "\55\76",                       // 6  ->
    "\154\141\142\145\154",         // 7  label
    null,    // 8  ID
    null,    // 9  OPEN_QUOTE  (matched as '"' at runtime)
    null,    // 10 QUOTED_ID
    null,    // 11 CLOSE_QUOTE (matched as '"' at runtime)
    "\173",  // 12 {
    "\175",  // 13 }
    "\73",   // 14 ;
    "\133",  // 15 [
    "\75",   // 16 =
    "\135",  // 17 ]
  };

  protected Token jjFillToken() {
    String im = jjstrLiteralImages[jjmatchedKind];
    String curTokenImage = (im == null) ? input_stream.GetImage() : im;
    Token t = Token.newToken(jjmatchedKind, curTokenImage);
    t.beginLine   = input_stream.getBeginLine();
    t.beginColumn = input_stream.getBeginColumn();
    t.endLine     = input_stream.getEndLine();
    t.endColumn   = input_stream.getEndColumn();
    return t;
  }

  /** Constructor. */
  public LTSParserTokenManager(SimpleCharStream stream) {
    input_stream = stream;
  }

  /** Constructor with lex state. */
  public LTSParserTokenManager(SimpleCharStream stream, int lexState) {
    this(stream);
    SwitchTo(lexState);
  }

  public void ReInit(SimpleCharStream stream) {
    input_stream = stream;
    curLexState  = defaultLexState;
    jjround      = 0x80000001;
    jjrounds[0]  = 0x80000000;
  }

  public void ReInit(SimpleCharStream stream, int lexState) {
    ReInit(stream);
    SwitchTo(lexState);
  }

  public void SwitchTo(int lexState) {
    if (lexState < 0 || lexState > 1)
      throw new TokenMgrError("Invalid lexical state: " + lexState, TokenMgrError.INVALID_LEXICAL_STATE);
    curLexState = lexState;
  }

  /** Get the next Token. */
  public Token getNextToken() {
    for (;;) {
      try {
        curChar = input_stream.BeginToken();
      } catch (Exception e) {
        jjmatchedKind = 0;
        jjmatchedPos  = -1;
        return jjFillToken();
      }

      if (curLexState == IN_LABEL) {
        // Inside a quoted label: collect all chars up to the closing '"'
        if (curChar == '"') {
          jjmatchedKind = CLOSE_QUOTE;
          jjmatchedPos  = 0;
          Token t = jjFillToken();
          curLexState = DEFAULT;
          return t;
        } else {
          // Read everything until '"'
          StringBuilder sb = new StringBuilder();
          sb.append((char) curChar);
          try {
            for (;;) {
              curChar = input_stream.readChar();
              if (curChar == '"') {
                input_stream.backup(1);
                break;
              }
              sb.append((char) curChar);
            }
          } catch (java.io.IOException e) { /* end of stream */ }
          jjmatchedKind = QUOTED_ID;
          jjmatchedPos  = sb.length() - 1;
          Token t = Token.newToken(QUOTED_ID, sb.toString());
          t.beginLine   = input_stream.getBeginLine();
          t.beginColumn = input_stream.getBeginColumn();
          t.endLine     = input_stream.getEndLine();
          t.endColumn   = input_stream.getEndColumn();
          return t;
        }
      }

      // DEFAULT state — skip whitespace
      if (curChar <= 32 && (curChar == ' ' || curChar == '\n' || curChar == '\t' || curChar == '\r')) {
        continue;
      }

      // Match literals and identifiers in DEFAULT state
      jjmatchedKind = 0x7fffffff;
      jjmatchedPos  = 0;

      switch (curChar) {
        case '"':  jjmatchedKind = OPEN_QUOTE; break;
        case '{':  jjmatchedKind = 12; break;
        case '}':  jjmatchedKind = 13; break;
        case ';':  jjmatchedKind = 14; break;
        case '[':  jjmatchedKind = 15; break;
        case '=':  jjmatchedKind = 16; break;
        case ']':  jjmatchedKind = 17; break;
        case '-': {
          try {
            int next = input_stream.readChar();
            if (next == '>') { jjmatchedKind = RARROW; jjmatchedPos = 1; }
            else { input_stream.backup(1); }
          } catch (java.io.IOException e) { /* ignore */ }
          break;
        }
        default: {
          // Try to match keyword or ID
          if (Character.isLetterOrDigit(curChar) || curChar == '_') {
            StringBuilder sb = new StringBuilder();
            sb.append((char) curChar);
            try {
              for (;;) {
                int next = input_stream.readChar();
                if (Character.isLetterOrDigit(next) || next == '_') {
                  sb.append((char) next);
                } else {
                  input_stream.backup(1);
                  break;
                }
              }
            } catch (java.io.IOException e) { /* end of stream */ }
            String word = sb.toString();
            if      (word.equals("digraph")) jjmatchedKind = DIGRAPH;
            else if (word.equals("label"))   jjmatchedKind = LABEL;
            else                              jjmatchedKind = ID;
            jjmatchedPos = word.length() - 1;
            Token t = Token.newToken(jjmatchedKind, word);
            t.beginLine   = input_stream.getBeginLine();
            t.beginColumn = input_stream.getBeginColumn();
            t.endLine     = input_stream.getEndLine();
            t.endColumn   = input_stream.getEndColumn();
            if (jjnewLexState[jjmatchedKind] != -1)
              curLexState = jjnewLexState[jjmatchedKind];
            return t;
          }
          break;
        }
      }

      if (jjmatchedKind == 0x7fffffff) {
        throw new TokenMgrError(false, curLexState,
            input_stream.getEndLine(), input_stream.getEndColumn(),
            input_stream.GetImage(), (char) curChar, TokenMgrError.LEXICAL_ERROR);
      }

      Token t = jjFillToken();
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
      return t;
    }
  }

  void SkipLexicalActions(Token matchedToken)  { }
  void MoreLexicalActions()                    { }
  void TokenLexicalActions(Token matchedToken) { }

  private void ReInitRounds() {
    jjround = 0x80000001;
    jjrounds[0] = 0x80000000;
  }

  static final int[] jjnextStates = { 0 };

  private void jjCheckNAdd(int state) {
    if (jjrounds[state] != jjround) {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
    }
  }
  private void jjAddStates(int start, int end) {
    do { jjstateSet[jjnewStateCnt++] = jjnextStates[start]; } while (start++ != end);
  }
  private void jjCheckNAddTwoStates(int s1, int s2) { jjCheckNAdd(s1); jjCheckNAdd(s2); }
}
