/* Generated By:JavaCC: Do not edit this line. LTSParserConstants.java */
package lkh.lts.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LTSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGRAPH = 5;
  /** RegularExpression Id. */
  int RARROW = 6;
  /** RegularExpression Id. */
  int LABEL = 7;
  /** RegularExpression Id. */
  int ID = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"digraph\"",
    "\"->\"",
    "\"label\"",
    "<ID>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"[\"",
    "\"=\"",
    "\"\\\"\"",
    "\"]\"",
  };

}
